version: '3.8'

services:
  mi_turno_app:
    build:
      context: ${FRONTEND_CONTEXT}
      dockerfile: ${FRONTEND_DOCKERFILE}
    container_name: ${FRONTEND_CONTAINER}
    image: ${FRONTEND_IMAGE}
    working_dir: /usr/src/app
    volumes:
      - ${FRONTEND_CONTEXT}:/usr/src/app
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - mi_turno_network
  mi_turno_servidor:
    build:
      context: ${SERVER_CONTEXT}
      dockerfile: ${SERVER_DOCKERFILE}
    container_name: ${SERVER_CONTAINER}
    image: ${SERVER_IMAGE}
    working_dir: /usr/src/app
    volumes:
      - ${SERVER_CONTEXT}:/usr/src/app
    ports:
      - "${SERVER_PORT}:8080"
    networks:
      - mi_turno_network
networks:
  mi_turno_network:
    driver: bridge