# Etapa 1: Construcción del proyecto
FROM node:16.20.2-alpine as build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build


# Etapa 2: Crear la imagen final
FROM node:16.20.2-alpine as runner
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/package*.json ./
RUN npm install --only=production  --no-cache --omit=dev

EXPOSE 8080

CMD ["npm", "start"]
